version: "3.8"

services:
  kafka-broker:
    image: apache/kafka:3.9.0
    hostname: broker
    container_name: kafka-broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_MAX_REQUEST_SIZE: 209715200 # 200MB, or set it to the desired size
      KAFKA_MESSAGE_MAX_BYTES: 209715200 # 200MB, or set it to the desired size
      KAFKA_REPLICATION_FETCH_MAX_BYTES: 209715200 # 200MB, or set it to the desired size

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka-broker:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      SERVER_SERVLET_CONTEXT_PATH: "/kafdrop"
    depends_on:
      - kafka-broker
    networks:
      - default

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - 5540:5540
    environment:
      REDIS_PASSWORD: password
    depends_on:
      - redis
    networks:
      - default
